---
title: "Practical Machine Learning README"
author: "Daddy The Runner"
date: "August 22, 2015"
output: 
  html_document: 
    keep_md: yes
---

This repository contains all of the files, execpt for the data files,
used to complete the Coursera Practical Machine Learning project.  Here
is a list of files along with a description:

Filename        | Description
----------------|------------
pml-readme.Rmd  | Source Rmd file for the README files
pml-readme.md   | RStudio generated markdown version of README
pml-readme.html | RStudio generated HTML version of README
pml-tools.R     | Helper functions written to perform this project
pml-report.Rmd  | Source Rmd file for the project report
pml-report.md   | RStudio generateed markdown version of the report
pml-report.html | RStudio generated HTML version of the report

The HTML report can be viewed on github using the following link:
(insert link here)

Alternatively, the HTML file can be downloaded from the repository
and viewed offline.